/**
 * Salary Calculation Engine for Andes Admin Portal
 *
 * Global Business Rules:
 * 1. Daily Wage = Monthly Salary / 26
 * 2. Weekly Off: Every Thursday is fixed weekly off for all workers.
 *    - Normal Thursday: If not worked, Thursday is Weekly Off (₹0 wage).
 *    - Thursday Worked: If worked, worker receives daily wage, marked as "Thursday Worked".
 * 3. Default Attendance:
 *    - Normal working days (Mon, Tue, Wed, Fri, Sat, Sun): Present by default (daily wage added).
 *    - Thursday: Weekly Off by default (₹0 wage).
 *    - Manager manually marks exceptions: Absent on normal days (₹0), or Thursday Worked on Thursdays (daily wage).
 * 4. Salary Rate Changes:
 *    - Monthly salaries can change mid-month with an effectiveDate.
 *    - Historical dates strictly use the rate effective on that date.
 * 5. Accruals & Idempotency:
 *    - All figures are derived deterministically from dated records.
 */

export const DAYS_IN_MONTH_DIVISOR = 26;
export const THURSDAY_DAY_INDEX = 4; // JavaScript Date.getDay(): 0=Sun, 1=Mon, ..., 4=Thu

/**
 * Checks if a date string ("YYYY-MM-DD") is a Thursday.
 */
export function isThursday(dateStr) {
  if (!dateStr) return false;
  const [year, month, day] = dateStr.split("-").map(Number);
  const d = new Date(year, month - 1, day);
  return d.getDay() === THURSDAY_DAY_INDEX;
}

/**
 * Gets day of week name short (e.g. "Mon", "Thu").
 */
export function getDayOfWeekName(dateStr) {
  if (!dateStr) return "";
  const [year, month, day] = dateStr.split("-").map(Number);
  const d = new Date(year, month - 1, day);
  return d.toLocaleDateString("en-US", { weekday: "short" });
}

/**
 * Calculates standard daily wage from monthly salary.
 */
export function getDailyWage(monthlySalary) {
  if (!monthlySalary || isNaN(monthlySalary)) return 0;
  return Number(monthlySalary) / DAYS_IN_MONTH_DIVISOR;
}

/**
 * Resolves the applicable monthly salary for a worker on a given date ("YYYY-MM-DD").
 * Looks up the latest salary rate in salaryHistory where effectiveDate <= dateStr.
 * Falls back to currentMonthlySalary.
 */
export function getApplicableSalary(worker, dateStr) {
  if (!worker) return 0;
  const history = Array.isArray(worker.salaryHistory) ? [...worker.salaryHistory] : [];
  
  if (history.length > 0) {
    // Sort descending by effectiveDate
    history.sort((a, b) => (b.effectiveDate || "").localeCompare(a.effectiveDate || ""));
    const match = history.find((h) => !h.effectiveDate || h.effectiveDate <= dateStr);
    if (match && typeof match.rate === "number" && !isNaN(match.rate)) {
      return match.rate;
    }
  }

  return Number(worker.currentMonthlySalary || 0);
}

/**
 * Resolves the attendance status for a worker on a specific date.
 * Default behavior:
 * - Before joiningDate: 'not_joined'
 * - If record exists: record.status ('present', 'absent', 'thursday_off', 'thursday_worked', 'half_day')
 * - If no record exists:
 *   - Thursday: 'thursday_off'
 *   - Other day: 'present'
 */
export function resolveAttendanceStatus(worker, dateStr, attendanceRecord) {
  if (!worker) return "absent";
  if (worker.joiningDate && dateStr < worker.joiningDate) {
    return "not_joined";
  }

  if (attendanceRecord && attendanceRecord.status) {
    return attendanceRecord.status;
  }

  // Default rule
  return isThursday(dateStr) ? "thursday_off" : "present";
}

/**
 * Calculates the salary cost generated by a worker on a specific date.
 */
export function calculateDailyCost(worker, dateStr, attendanceRecord) {
  const status = resolveAttendanceStatus(worker, dateStr, attendanceRecord);
  const monthlySalary = getApplicableSalary(worker, dateStr);
  const dailyWage = getDailyWage(monthlySalary);

  let cost = 0;
  let isWorked = false;

  switch (status) {
    case "present":
      cost = dailyWage;
      isWorked = true;
      break;
    case "thursday_worked":
      cost = dailyWage;
      isWorked = true;
      break;
    case "half_day":
      cost = dailyWage / 2;
      isWorked = true;
      break;
    case "thursday_off":
    case "absent":
    case "not_joined":
    default:
      cost = 0;
      isWorked = false;
      break;
  }

  return {
    date: dateStr,
    dayOfWeek: getDayOfWeekName(dateStr),
    isThursday: isThursday(dateStr),
    status,
    monthlySalary,
    dailyWage,
    cost,
    isWorked,
    note: attendanceRecord?.note || "",
  };
}

/**
 * Helper to get all dates in a month up to limitDate (inclusive).
 * yearMonth is "YYYY-MM".
 */
export function getDatesInMonth(yearMonth, limitDate = null) {
  const [yearStr, monthStr] = yearMonth.split("-");
  const year = parseInt(yearStr, 10);
  const month = parseInt(monthStr, 10); // 1-indexed

  const totalDays = new Date(year, month, 0).getDate();
  const dates = [];

  for (let d = 1; d <= totalDays; d++) {
    const dayStr = String(d).padStart(2, "0");
    const dateStr = `${yearStr}-${monthStr.padStart(2, "0")}-${dayStr}`;
    if (limitDate && dateStr > limitDate) break;
    dates.push(dateStr);
  }

  return dates;
}

/**
 * Calculates the comprehensive monthly summary for a single worker.
 *
 * @param {Object} worker
 * @param {string} yearMonth - "YYYY-MM"
 * @param {Map<string, Object>} attendanceMap - Key: `${workerId}_${date}`
 * @param {Array<Object>} adjustments - Adjustments for this worker & month
 * @param {Array<Object>} payments - Payments for this worker & month
 * @param {string} asOfDate - Date up to which to compute (e.g. today or month end)
 */
export function calculateMonthSummary(
  worker,
  yearMonth,
  attendanceMap = new Map(),
  adjustments = [],
  payments = [],
  asOfDate = null
) {
  const currentMonth = new Date().toISOString().slice(0, 7);
  const todayStr = new Date().toISOString().slice(0, 10);

  // If calculating for current month, calculate up to today by default (or end of month if specified)
  const isCurrentMonth = yearMonth === currentMonth;
  const maxCalculationDate = asOfDate || (isCurrentMonth ? todayStr : null);

  const dates = getDatesInMonth(yearMonth, maxCalculationDate);

  let normalWorkingDays = 0;
  let daysWorked = 0;
  let thursdaysWorked = 0;
  let weeklyOffs = 0;
  let absences = 0;
  let halfDays = 0;
  let regularSalary = 0;

  const dailyBreakdown = dates.map((dateStr) => {
    const record = attendanceMap.get(`${worker.id}_${dateStr}`);
    const dailyInfo = calculateDailyCost(worker, dateStr, record);

    if (dailyInfo.status !== "not_joined") {
      if (dailyInfo.isThursday) {
        if (dailyInfo.status === "thursday_worked") {
          thursdaysWorked += 1;
          daysWorked += 1;
        } else {
          weeklyOffs += 1;
        }
      } else {
        normalWorkingDays += 1;
        if (dailyInfo.status === "present") {
          daysWorked += 1;
        } else if (dailyInfo.status === "half_day") {
          daysWorked += 0.5;
          halfDays += 1;
        } else if (dailyInfo.status === "absent") {
          absences += 1;
        }
      }
      regularSalary += dailyInfo.cost;
    }

    return dailyInfo;
  });

  // Today's cost & status
  const todayRecord = attendanceMap.get(`${worker.id}_${todayStr}`);
  const todayInfo = calculateDailyCost(worker, todayStr, todayRecord);

  // Calculate Overtime, Additional Payments, Deductions
  let overtime = 0;
  let additionalPayments = 0;
  let deductions = 0;

  (adjustments || []).forEach((adj) => {
    const amt = Number(adj.amount || 0);
    if (adj.type === "overtime") overtime += amt;
    else if (adj.type === "additional_payment" || adj.type === "extra") additionalPayments += amt;
    else if (adj.type === "deduction") deductions += amt;
  });

  // Total Accrued
  const totalAccrued = regularSalary + overtime + additionalPayments - deductions;

  // Payments Made
  const totalPaid = (payments || []).reduce((sum, p) => sum + Number(p.amount || 0), 0);
  const remainingAmount = Math.max(0, totalAccrued - totalPaid);

  const currentSalaryRate = getApplicableSalary(worker, todayStr);
  const currentDailyWage = getDailyWage(currentSalaryRate);

  return {
    workerId: worker.id,
    workerName: worker.name,
    role: worker.role,
    joiningDate: worker.joiningDate,
    currentMonthlySalary: currentSalaryRate,
    currentDailyWage,
    daysWorked,
    normalWorkingDays,
    thursdaysWorked,
    weeklyOffs,
    absences,
    halfDays,
    todayCost: todayInfo.cost,
    todayStatus: todayInfo.status,
    todayWage: todayInfo.dailyWage,
    regularSalary,
    overtime,
    additionalPayments,
    deductions,
    totalAccrued,
    totalPaid,
    remainingAmount,
    dailyBreakdown,
  };
}

/**
 * Calculates aggregate dashboard summary metrics for all active workers.
 */
export function calculateDashboardMetrics(
  workers = [],
  yearMonth,
  attendanceMap = new Map(),
  adjustments = [],
  payments = []
) {
  const activeWorkers = workers.filter((w) => w.status !== "inactive");

  let totalWorkers = activeWorkers.length;
  let todaySalaryExpense = 0;
  let currentMonthAccrued = 0;
  let totalOvertime = 0;
  let totalAdditionalPayments = 0;
  let totalDeductions = 0;
  let totalPaid = 0;
  let totalRemaining = 0;

  const workerSummaries = activeWorkers.map((worker) => {
    const workerAdjs = adjustments.filter(
      (a) => a.workerId === worker.id && (!a.month || a.month === yearMonth)
    );
    const workerPayments = payments.filter(
      (p) => p.workerId === worker.id && (!p.month || p.month === yearMonth)
    );

    const summary = calculateMonthSummary(
      worker,
      yearMonth,
      attendanceMap,
      workerAdjs,
      workerPayments
    );

    todaySalaryExpense += summary.todayCost;
    currentMonthAccrued += summary.totalAccrued;
    totalOvertime += summary.overtime;
    totalAdditionalPayments += summary.additionalPayments;
    totalDeductions += summary.deductions;
    totalPaid += summary.totalPaid;
    totalRemaining += summary.remainingAmount;

    return summary;
  });

  return {
    totalWorkers,
    todaySalaryExpense,
    currentMonthAccrued,
    totalOvertime,
    totalAdditionalPayments,
    totalDeductions,
    totalPaid,
    totalRemaining,
    workerSummaries,
  };
}

/**
 * Format currency helper in INR (₹).
 */
export function formatCurrency(amount, decimals = 0) {
  if (amount === undefined || amount === null || isNaN(amount)) return "₹0";
  return `₹${Number(amount).toLocaleString("en-IN", {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  })}`;
}
